pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'net.ltgt.errorprone' version '5.1.1'
        id 'de.thetaphi.forbiddenapis' version "${forbiddenApisVersion}"
    }
}

include ':FtcRobotController'
include ':TeamCode'
include ':simcore'
